image: docker:stable-git

services:
  - docker:dind

stages:
  - build

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  BASEIMAGE: registry.gitlab.com/koha-community/docker/koha-docker

before_script:
  - docker login -u $PAUSER -p $PATOKEN registry.gitlab.com

build:
  stage: build
  script:
    - docker build --cache-from $BASEIMAGE:latest -t $BASEIMAGE:latest -t $BASEIMAGE:$CI_COMMIT_TAG -t $BASEIMAGE:$CI_COMMIT_SHA .
    - docker push $BASEIMAGE:$CI_COMMIT_SHA
    - docker push $BASEIMAGE:$CI_COMMIT_TAG
    - docker push $BASEIMAGE:latest
  only:
    - tags
