version: '3'
services:
    db:
        image: mariadb:10.3
        restart: always
        env_file:
            - .env
        volumes:
            - ${DB_VOLUME:-db-data}:/var/lib/mysql
        networks:
            - kohanet
    es:
        image: koha/elasticsearch-icu
        environment:
            - cluster.name=docker-cluster
            - bootstrap.memory_lock=true
            - xpack.security.enabled=false
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        networks:
            - kohanet


    koha:
        build: .
        
        depends_on:
            - db
            - es
            - memcached
        cap_add:
            - ALL
        tmpfs:
            - /cover_db
            - /tmp
        env_file:
            - .env
        environment:
            USE_APACHE2: 1
            USE_BACKEND: 1
            USE_SIP: 1
            USE_CRON: 0
            USE_Z3950: 0
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        networks:
            kohanet:
              aliases:
                    - "${KOHA_INTRANET_PREFIX}${KOHA_INSTANCE}${KOHA_INTRANET_SUFFIX}${KOHA_DOMAIN}"
                    - "${KOHA_OPAC_PREFIX}${KOHA_INSTANCE}${KOHA_OPAC_SUFFIX}${KOHA_DOMAIN}"

        ports:
            - "6001:6001" 
            - "8081:8081"
            - "8080:8080"


    memcached:
        image: memcached
        command: memcached -m 64m
        networks:
            - kohanet
volumes:
    db-data:
networks:
    kohanet:
